import json

def applicationConfig():
	_config = {
		"IS_APPLICATION_IN_SANDBOX" : "true",
	}

	_jsonSandBox = {
	
		"USER" :"muru_sgbus_api1.pp.com",
		"PWD" :"TBXQWJTU9RFEVPPG",
		"SIGNATURE" :"AFcWxV21C7fd0v3bYYYRCpSSRl31ALsxBva-lMS-1Q0ty2DhT7QBTKYd",
		"URL" :"https://api-3t.sandbox.paypal.com/nvp",
		"BN_CODE":"PP-DemoPortal-EC-JSV4-python",
		"VERSION":"204.0",
		"SetEC_METHOD":"SetExpressCheckout",
		"DoEC_METHOD":"DoExpressCheckoutPayment",
		"GetEC_METHOD":"GetExpressCheckoutDetails",
		"CANCEL_URL":"cancelUrl",
		"RETURN_URL":"cancelUrl",
		"ACTION":"sale"


	}

	_jsonLive = {
		"USER" :"USER",
		"PWD" :"PWD",
		"SIGNATURE" :"SIGNATURE",
		"URL" :"https://api-3t.paypal.com/nvp",
		"BN_CODE":"PP-DemoPortal-EC-JSV4-python",
		"VERSION":"204.0",
		"SetEC_METHOD":"SetExpressCheckout",
		"DoEC_METHOD":"DoExpressCheckoutPayment",
		"GetEC_METHOD":"GetExpressCheckoutDetails",
		"CANCEL_URL":"cancelUrl",
		"RETURN_URL":"cancelUrl",
		"ACTION":"sale"
	}

	if _config['IS_APPLICATION_IN_SANDBOX'] == 'true':
		print "T"
		return _jsonSandBox
	else:
		print "F"
		return _jsonLive

def getSetExpressCheckoutTemplate():
	return "METHOD=METHOD&USER=USER&PWD=PWD&SIGNATURE=SIGNATURE&VERSION=VERSION&RETURNURL=RETURNURL&CANCELURL=CANCELURL&PAYMENTREQUEST_0_PAYMENTACTION=PAYMENTREQUEST_0_PAYMENTACTION&&PAYMENTREQUEST_0_CURRENCYCODE=PAYMENTREQUEST_0_CURRENCYCODE&PAYMENTREQUEST_0_CURRENCYCODE=PAYMENTREQUEST_0_CURRENCYCODE&PAYMENTREQUEST_0_AMT=PAYMENTREQUEST_0_AMT&PAYMENTREQUEST_0_ITEMAMT=PAYMENTREQUEST_0_ITEMAMT&L_PAYMENTREQUEST_0_NAME0=L_PAYMENTREQUEST_0_NAME0&L_PAYMENTREQUEST_0_NUMBER0=L_PAYMENTREQUEST_0_NUMBER0&L_PAYMENTREQUEST_0_QTY0=L_PAYMENTREQUEST_0_QTY0&L_PAYMENTREQUEST_0_AMT0=L_PAYMENTREQUEST_0_AMT0&PAYMENTREQUEST_0_INSURANCEAMT=PAYMENTREQUEST_0_INSURANCEAMT&PAYMENTREQUEST_0_TAXAMT=PAYMENTREQUEST_0_TAXAMT&PAYMENTREQUEST_0_SHIPDISCAMT=PAYMENTREQUEST_0_SHIPDISCAMT&PAYMENTREQUEST_0_HANDLINGAMT=PAYMENTREQUEST_0_HANDLINGAMT&PAYMENTREQUEST_0_SHIPPINGAMT=PAYMENTREQUEST_0_SHIPPINGAMT&BUTTONSOURCE=BUTTONSOURCE"

def getGetEcPaymentPayloadTemplate():
	return "USER=USER&PWD=PWD&SIGNATURE=SIGNATURE&TOKEN=TOKEN&METHOD=METHOD&VERSION=VERSION"

def getDoEcPaymentPayloadTemplate():
	return "USER=USER&PWD=PWD&SIGNATURE=SIGNATURE&VERSION=VERSION&METHOD=METHOD&TOKEN=TOKEN&PAYERID=PAYERID&PAYMENTREQUEST_0_PAYMENTACTION=PAYMENTREQUEST_0_PAYMENTACTION&PAYMENTREQUEST_0_CURRENCYCODE=PAYMENTREQUEST_0_CURRENCYCODE&PAYMENTREQUEST_0_AMT=PAYMENTREQUEST_0_AMT&PAYMENTREQUEST_0_ITEMAMT=PAYMENTREQUEST_0_ITEMAMT&L_PAYMENTREQUEST_0_NAME0=L_PAYMENTREQUEST_0_NAME0&L_PAYMENTREQUEST_0_NUMBER0=1&L_PAYMENTREQUEST_0_QTY0=1&L_PAYMENTREQUEST_0_AMT0=L_PAYMENTREQUEST_0_AMT0"